apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eci-tools
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: eci/environments/tools
    repoURL: https://github.com/eci-cicd/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
